/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.eketal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmFormalParameter;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ev Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.icesi.eketal.eketal.EvDecl#getParams <em>Params</em>}</li>
 *   <li>{@link co.edu.icesi.eketal.eketal.EvDecl#getEventos <em>Eventos</em>}</li>
 * </ul>
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getEvDecl()
 * @model
 * @generated
 */
public interface EvDecl extends Decl
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.common.types.JvmFormalParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getEvDecl_Params()
   * @model containment="true"
   * @generated
   */
  EList<JvmFormalParameter> getParams();

  /**
   * Returns the value of the '<em><b>Eventos</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.icesi.eketal.eketal.EventExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Eventos</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventos</em>' containment reference list.
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getEvDecl_Eventos()
   * @model containment="true"
   * @generated
   */
  EList<EventExpression> getEventos();

} // EvDecl
