/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.eketal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getEventPredicate()
 * @model
 * @generated
 */
public interface EventPredicate extends EObject
{
} // EventPredicate
