/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.eketal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.icesi.eketal.eketal.Group#getHosts <em>Hosts</em>}</li>
 * </ul>
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getGroup()
 * @model
 * @generated
 */
public interface Group extends Decl
{
  /**
   * Returns the value of the '<em><b>Hosts</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.icesi.eketal.eketal.Host}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hosts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hosts</em>' containment reference list.
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getGroup_Hosts()
   * @model containment="true"
   * @generated
   */
  EList<Host> getHosts();

} // Group
