/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.eketal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.icesi.eketal.eketal.Rc#getAsyncex <em>Asyncex</em>}</li>
 *   <li>{@link co.edu.icesi.eketal.eketal.Rc#getPos <em>Pos</em>}</li>
 *   <li>{@link co.edu.icesi.eketal.eketal.Rc#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getRc()
 * @model
 * @generated
 */
public interface Rc extends Decl
{
  /**
   * Returns the value of the '<em><b>Asyncex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Asyncex</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asyncex</em>' attribute.
   * @see #setAsyncex(String)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getRc_Asyncex()
   * @model
   * @generated
   */
  String getAsyncex();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.Rc#getAsyncex <em>Asyncex</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asyncex</em>' attribute.
   * @see #getAsyncex()
   * @generated
   */
  void setAsyncex(String value);

  /**
   * Returns the value of the '<em><b>Pos</b></em>' attribute.
   * The literals are from the enumeration {@link co.edu.icesi.eketal.eketal.Pos}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pos</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos</em>' attribute.
   * @see co.edu.icesi.eketal.eketal.Pos
   * @see #setPos(Pos)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getRc_Pos()
   * @model
   * @generated
   */
  Pos getPos();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.Rc#getPos <em>Pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos</em>' attribute.
   * @see co.edu.icesi.eketal.eketal.Pos
   * @see #getPos()
   * @generated
   */
  void setPos(Pos value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Body)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getRc_Body()
   * @model containment="true"
   * @generated
   */
  Body getBody();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.Rc#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Body value);

} // Rc
