/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.ui;

import co.edu.icesi.eketal.ui.AbstractEketalUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EketalUiModule extends AbstractEketalUiModule {
  public EketalUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
