/*
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.ui;

import co.edu.icesi.eketal.ui.internal.EketalActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EketalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EketalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EketalActivator.getInstance().getInjector(EketalActivator.CO_EDU_ICESI_EKETAL_EKETAL);
	}
	
}
