/*
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class EketalUiModule extends AbstractEketalUiModule {
}
