/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal;

import co.edu.icesi.eketal.AbstractEketalRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EketalRuntimeModule extends AbstractEketalRuntimeModule {
}
