/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.ui.contentassist;

import co.edu.icesi.eketal.ui.contentassist.AbstractEketalProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EketalProposalProvider extends AbstractEketalProposalProvider {
}
