/*
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class EketalScopeProvider extends AbstractEketalScopeProvider {

}
