/*
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EketalRuntimeModule extends AbstractEketalRuntimeModule {
}
